#!/usr/bin/env python3
# A web server to echo back a request's headers and data.
#
# Usage: ./webserver
#        ./webserver 0.0.0.0:5000

import sys
from http.server import BaseHTTPRequestHandler, HTTPServer

BIND_HOST = "localhost"
PORT = 8008


class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.write_response(b"")

    def do_HEAD(self):
        self.write_response(b"")

    def do_POST(self):
        self.handle_request_with_body()

    def do_PUT(self):
        self.handle_request_with_body()

    def do_PATCH(self):
        self.handle_request_with_body()

    def do_DELETE(self):
        self.handle_request_with_body()

    def handle_request_with_body(self):
        content_length = int(self.headers.get("content-length", 0))
        body = self.rfile.read(content_length)

        self.write_response(body)

    def write_response(self, content):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(content)

        print(self.headers)
        print(content.decode("utf-8"))


if len(sys.argv) > 1:
    if sys.argv[1] in ("-v", "--version", "version"):
        print("0.4.1")
        sys.exit()

    arg = sys.argv[1].split(":")
    BIND_HOST = arg[0]
    PORT = int(arg[1])

print(f"Listening on http://{BIND_HOST}:{PORT}\n")

httpd = HTTPServer((BIND_HOST, PORT), SimpleHTTPRequestHandler)
httpd.serve_forever()
