name: "CI"

on: "push"

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Python 3.11"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: "Lint extension"
        run: |
          pip install ruff
          ruff check webserver
          ruff format --diff webserver
